task: crs
# model
model: kerl
dataset: inspired
tokenizer: bart
# dataset
context_truncate: 256
response_truncate: 64
descr_truncate: 40
max_entity_length: 32
use_description: true
# rec model
use_context: true
text_pooling_type: attention
text_pooling_head: 4
# kg
kg_embedding_dim: 256
n_bases: 8
position_encoding: true
max_n_positions: 40
use_kg_loss: true
kg_config:
    neg_batch_size: 128
    kg_batch_size: 512
    kg_margin: 10
    pretrain_lr: 0.00008
    pretrain_bart_lr: 0.00008
    weight_decay: 0.003
    epoch: 4
    pretrain_reload: true
    pretrain_model_path: "saved/inspired/pretrained/last.ckpt"
rec:
    epochs: 31
    batch_size: 128
    lr: 0.0006
    bart_lr: 0.00002
    weight_decay: 0.001
    early_stop: True
    early_stop_patience: 5
    num_cycles: 0.5
    rec_reload: true
    rec_model_path: "saved/inspired/rec/best.ckpt"
conv:
    epochs: 10
    batch_size: 128
    lr: 0.0002
    weight_decay: 0.001
    early_stop: True
    early_stop_patience: 3
    num_cycles: 0.5
    conv_reload: true
    conv_model_path: "saved/inspired/gen/best.ckpt"
seed: 10
# logger
logger: wandb
additional_notes: "kerl_inspired"
# restore
restore: false